### ISSUE TITLE
Add links to state and territory portals

### ISSUE THREAD

**Issue by gordongrace** [govau/australia-gov-au-static#180]
Re-use material from https://www.gov.au/

**Comment by svict4** [comment]
Are you linking to the coronavirus portals/pages directly? Or just the health sites for each state and territory?

https://preview.nsw.gov.au/covid-19
https://www.dhhs.vic.gov.au/coronavirus
https://www.wa.gov.au/government/coronavirus-covid-19

**Comment by gordongrace** [comment]
Likely to be:

`
<ul role="list">
	<li>
		<a href="https://preview.nsw.gov.au/covid-19">New South Wales</a>
	</li>
	<li>
		<a href="http://www.coronavirus.vic.gov.au/">Victoria</a>
	</li>
	<li>
		<a href="https://www.qld.gov.au/health/conditions/health-alerts/coronavirus-covid-19">Queensland</a>
	</li>
	<li>
		<a href="https://www.sahealth.sa.gov.au/wps/wcm/connect/public+content/sa+health+internet/health+topics/health+topics+a+-+z/covid+2019/community/information+for+the+community+-+covid-19">South Australia</a>
	</li>
	<li>
		<a href="https://imsva91-ctp.trendmicro.com/wis/clicktime/v1/query?url=http%3a%2f%2fwww.wa.gov.au%2fgovernment%2fcoronavirus%2dcovid%2d19&umid=1484140B-A17B-D305-9BAB-8CE2FE0CA47E&auth=70c51ee34093367b6db11dc77fd1225c2c560473-d69ea67a569fe9a6237781caa27ef97e8eec4ec5">Western Australia</a>
	</li>
	<li>
		<a href="https://www.dhhs.tas.gov.au/publichealth/communicable_diseases_prevention_unit/infectious_diseases/coronavirus">Tasmania</a>
	</li>
	<li>
		<a href="http://coronavirus.nt.gov.au/">Northern Territory</a>
	</li>
	<li>
		<a href="http://health.act.gov.au/about-our-health-system/novel-coronavirus-covid-19">Australian Capital Territory</a>
	</li>
</ul>
`
